services:
#  postgres:
#    container_name: postgres-rs
#    image: postgres
#    environment:
#      POSTGRES_USER: postgres.gifkpefspdzsjefvqfxx
#      POSTGRES_PASSWORD: orange946312mango
#      PGDATA: /var/lib/postgresql/data
#      POSTGRES_DB: orange946312mango
#    volumes:
#      - postgres:/data/postgres
#    ports:
#      - 5432:5432
#    networks:
#      - spring-demo
#    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-rs
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local